#!/usr/bin/env python3
"""Daily systematic market scan. Pulls prices for a liquid universe, computes
trend/momentum/volatility signals, ranks them, and writes reports/YYYY-MM-DD.md.
Run: .venv/bin/python research/scan.py
"""
import json, sys, datetime as dt
from pathlib import Path
import numpy as np, pandas as pd, yfinance as yf

def download_aligned(tickers, **kw):
    """yfinance download where crypto (7-day) tickers are aligned to the equity trading-day index.
    Prevents calendar-day indexes that forward-fill equities across weekends (found 2026-09-04)."""
    import yfinance as yf, pandas as pd
    crypto = [t for t in tickers if t.endswith("-USD")]; eq = [t for t in tickers if t not in crypto]
    px = yf.download(eq, auto_adjust=True, progress=False, **kw)["Close"]
    if isinstance(px, pd.Series): px = px.to_frame(eq[0])
    px = px.dropna(how="all")
    if crypto:
        cx = yf.download(crypto, auto_adjust=True, progress=False, **kw)["Close"]
        if isinstance(cx, pd.Series): cx = cx.to_frame(crypto[0])
        px = px.join(cx.reindex(px.index, method="ffill"))
    return px.ffill()

ROOT = Path(__file__).resolve().parents[1]
UNIVERSE = json.loads((ROOT / "research" / "universe.json").read_text())
TICKERS = sorted({t for grp in UNIVERSE.values() for t in grp})

def rsi(s, n=14):
    d = s.diff(); up = d.clip(lower=0).ewm(alpha=1/n, adjust=False).mean()
    dn = (-d.clip(upper=0)).ewm(alpha=1/n, adjust=False).mean()
    return 100 - 100 / (1 + up / dn.replace(0, np.nan))

def main():
    px = download_aligned(TICKERS, period="15mo", threads=True)
    last = px.index[-1].date()
    rows = []
    for t in px.columns:
        s = px[t].dropna()
        if len(s) < 230: continue
        c = s.iloc[-1]
        r = lambda n: c / s.iloc[-n-1] - 1
        mom_12_1 = s.iloc[-22] / s.iloc[-253] - 1          # classic 12-1 momentum
        vol20 = s.pct_change().iloc[-20:].std() * np.sqrt(252)
        hi52 = s.iloc[-252:].max()
        ma200 = s.rolling(200).mean().iloc[-1]
        rows.append(dict(ticker=t, close=round(c,2), r1d=r(1), r1m=r(21), r3m=r(63), r6m=r(126),
            mom_12_1=mom_12_1, above_50=c > s.rolling(50).mean().iloc[-1],
            above_200=c > ma200, ma200=round(ma200, 4), d200=c / ma200 - 1, rsi14=rsi(s).iloc[-1],
            off_52w_high=c / hi52 - 1, vol20=vol20))
    df = pd.DataFrame(rows).set_index("ticker")
    # Composite: risk-adjusted momentum (12-1 and 6m) scaled by vol, trend filter.
    # INFORMATIONAL ONLY since RULES v2 (2026-09-06): the live book neither ranks nor filters on
    # it. v2 holds every name inside the 200d +/-3% band; d200 above is that distance, but the
    # band is path-dependent, so the held set is computed by products/bot/bot.py from the
    # full-history cache data/prices.csv, not from this 15-month window.
    df["score"] = (df.mom_12_1.rank(pct=True) + df.r6m.rank(pct=True) + df.r3m.rank(pct=True)) / 3
    df["score"] = df.score * (0.5 + 0.5 * df.above_200.astype(float)) / df.vol20.clip(lower=0.08) ** 0.5
    df = df.sort_values("score", ascending=False)
    # Breadth
    breadth = f"{df.above_200.mean():.0%} of universe above 200d MA, {df.above_50.mean():.0%} above 50d MA"
    pct = lambda x: f"{x:+.1%}"
    def table(d):
        hdr = "| Ticker | Close | 1d | 1m | 3m | 6m | 12-1 Mom | RSI | Off 52w Hi | Vol20 | >200d |\n|---|---|---|---|---|---|---|---|---|---|---|\n"
        return hdr + "\n".join(f"| {t} | {r.close} | {pct(r.r1d)} | {pct(r.r1m)} | {pct(r.r3m)} | {pct(r.r6m)} | {pct(r.mom_12_1)} | {r.rsi14:.0f} | {pct(r.off_52w_high)} | {r.vol20:.0%} | {'Y' if r.above_200 else 'N'} |" for t, r in d.iterrows())
    spy = df.loc["SPY"] if "SPY" in df.index else None
    out = [f"# Market Scan — {last}", "", f"**Breadth:** {breadth}",
           f"**SPY:** 1d {pct(spy.r1d)}, 1m {pct(spy.r1m)}, 3m {pct(spy.r3m)}, RSI {spy.rsi14:.0f}, {pct(spy.off_52w_high)} off 52w high" if spy is not None else "",
           "", "_Ranking below is informational. The live paper book (research/RULES.md v2) holds"
           " every name inside its 200d ±3% band at 0.75/N of NAV and does not use this score._",
           "", "## Top 15 by risk-adjusted momentum", table(df.head(15)),
           "", "## Bottom 10 (weakest trend)", table(df.tail(10)),
           "", "## Oversold in uptrend (RSI<35 and above 200d) — mean-reversion candidates",
           table(df[(df.rsi14 < 35) & df.above_200]) if ((df.rsi14 < 35) & df.above_200).any() else "_none_",
           "", "## Sector ETF ranking", table(df.loc[[t for t in UNIVERSE["sectors"] if t in df.index]]),
           "", "_Generated by research/scan.py. Research output only — not investment advice._"]
    (ROOT / "reports").mkdir(exist_ok=True)
    path = ROOT / "reports" / f"{last}.md"
    path.write_text("\n".join(out))
    df.to_csv(ROOT / "reports" / f"{last}.csv")
    print(f"wrote {path}\n{breadth}\nTop 5: {', '.join(df.head(5).index)}")

if __name__ == "__main__":
    main()
