"""
Customer alias list for INFO-1: large US-listed companies (including US-listed ADRs)
and a few unambiguous wholly owned subsidiaries, mapped to the listed parent.

Built from (1) the brief's starter list and (2) the most frequent customer names in a
random discovery sample of 1,500 concentration-disclosing 10-Ks (data/discovery_names.csv).

Each entry:
  id         customer id used in the link table
  spell      plain spellings (used for the full-text-search phrase templates and, after
             escaping, for the in-document regex; case-sensitive, hyphen/space/apostrophe
             tolerant)
  tickers    [(yahoo_ticker, first_month, last_month)]: which price series gives the
             listed parent's return in which months (None = open). A customer month with
             no listed series is not a signal (the customer was not listed / no price).
  not_after  regex: an alias match followed by this is not the customer (e.g. "Apple
             Hospitality")
  not_before regex: an alias match preceded by this is not the customer
Treated as no link (never in this list): governments and agencies, unnamed customers
("Customer A", "a distributor"), private companies, and companies listed only abroad.
"""
from __future__ import annotations

import re

C = []


def add(id_, spell, tickers, not_after=None, not_before=None, fts=None):
    C.append(dict(id=id_, spell=spell, tickers=tickers, not_after=not_after, not_before=not_before,
                  fts=fts if fts is not None else spell))


# ------------------------------------------------------------------ retail
add("WMT", ["Walmart", "Wal-Mart", "Wal Mart", "WalMart", "Sam's Club", "Sams Club", "Sam's Wholesale Club"],
    [("WMT", None, None)], not_after=r"^\s*(?:de M[eé]xico|Mexico|Canada|Chile)")
add("TGT", ["Target Corporation", "Target Corp", "Target Stores", "Target"], [("TGT", None, None)],
    not_after=r"^\s*(?:market|markets|customer|customers|audience|price|prices|date|level|range|segment|demographic|consumer|consumers|company|companies|group|population|rate|return|allocation|zone|area|areas|acquisition|acquisitions|leverage|ratio|capital|and\s+[a-z])\b",
    fts=["Target Corporation", "Target Corp", "Target Stores", "Target"])
add("HD", ["The Home Depot", "Home Depot"], [("HD", None, None)])
add("LOW", ["Lowe's", "Lowes", "Lowe s"], [("LOW", None, None)])
add("COST", ["Costco"], [("COST", None, None)])
add("BBY", ["Best Buy"], [("BBY", None, None)])
add("DG", ["Dollar General"], [("DG", None, None)])
add("DLTR", ["Dollar Tree"], [("DLTR", None, None)])
add("DLTR_FDO", ["Family Dollar"], [("DLTR", "2015-08-01", None)])  # pre-merger FDO: no Yahoo series
add("KR", ["Kroger"], [("KR", None, None)])
add("CVS", ["CVS", "Caremark"], [("CVS", None, None)])
add("WBA", ["Walgreens", "Walgreen", "Walgreens Boots Alliance"], [("WBA", None, "2025-08-01")])
add("AMZN", ["Amazon", "Amazon.com", "Amazon Web Services"], [("AMZN", None, None)],
    not_after=r"^\s*(?:Marketplace|marketplace|Seller|Vendor Express|Prime Video|Prime)\b")
add("AMZN_WFM", ["Whole Foods"], [("AMZN", "2017-09-01", None)])
add("KSS", ["Kohl's", "Kohls"], [("KSS", None, None)])
add("M", ["Macy's", "Macys"], [("M", None, None)])
add("JWN", ["Nordstrom"], [("JWN", None, "2025-05-01")])
add("TJX", ["TJX", "T.J. Maxx", "TJ Maxx", "Marshalls"], [("TJX", None, None)])
add("ROST", ["Ross Stores"], [("ROST", None, None)])
add("TSCO", ["Tractor Supply"], [("TSCO", None, None)])
add("AZO", ["AutoZone"], [("AZO", None, None)])
add("ORLY", ["O'Reilly Automotive", "O'Reilly Auto", "O Reilly Automotive"], [("ORLY", None, None)])
add("AAP", ["Advance Auto Parts", "Advance Auto"], [("AAP", None, None)])
add("DKS", ["Dick's Sporting Goods", "Dicks Sporting Goods"], [("DKS", None, None)])
add("ODP", ["Office Depot", "OfficeMax", "ODP Corporation"], [("ODP", None, "2025-09-01")])
add("ULTA", ["Ulta Beauty", "Ulta Salon", "Ulta"], [("ULTA", None, None)])
add("BJ", ["BJ's Wholesale", "BJs Wholesale"], [("BJ", None, None)])
add("ACI", ["Albertsons", "Safeway"], [("ACI", "2020-07-01", None)])
add("SHLD", ["Sears", "Kmart"], [("SHLD", None, "2018-10-01")], not_after=r"^\s*(?:Canada|Hometown)")
add("JCP", ["J.C. Penney", "JCPenney", "JC Penney", "J. C. Penney"], [("JCP", None, "2020-05-01")])
add("RAD", ["Rite Aid"], [("RAD", None, "2023-10-01")])
add("BBBY", ["Bed Bath & Beyond", "Bed Bath and Beyond"], [("BBBY", None, "2023-04-01")])
add("GME", ["GameStop"], [("GME", None, None)])
add("CHWY", ["Chewy"], [("CHWY", None, None)])
add("W", ["Wayfair"], [("W", None, None)])
add("EBAY", ["eBay"], [("EBAY", None, None)])
add("QVC", ["QVC"], [("QRTEA", None, None)])
add("WOOF", ["Petco"], [("WOOF", "2021-02-01", None)])
add("PETM", ["PetSmart"], [("PETM", None, "2015-03-01")])
add("SPLS", ["Staples"], [("SPLS", None, "2017-09-01")])
add("DDS", ["Dillard's", "Dillards"], [("DDS", None, None)])
add("BURL", ["Burlington Coat Factory", "Burlington Stores"], [("BURL", None, None)])
add("BIG", ["Big Lots"], [("BIG", None, "2024-09-01")])
add("FIVE", ["Five Below"], [("FIVE", None, None)])
add("OLLI", ["Ollie's Bargain"], [("OLLI", None, None)])
add("ASO", ["Academy Sports"], [("ASO", None, None)])
add("SYY", ["Sysco"], [("SYY", None, None)])
add("USFD", ["US Foods", "U.S. Foods"], [("USFD", None, None)])
add("PFGC", ["Performance Food Group"], [("PFGC", None, None)])
add("UNFI", ["United Natural Foods", "UNFI"], [("UNFI", None, None)])
add("UNFI_SVU", ["Supervalu", "SUPERVALU"], [("UNFI", "2018-11-01", None)])  # pre-merger SVU: no Yahoo series
add("CORE", ["Core-Mark"], [("CORE", None, "2021-09-01")])
add("BRK", ["McLane"], [("BRK-B", None, None)])

# ------------------------------------------------------------------ health-care distribution / payers
add("MCK", ["McKesson"], [("MCK", None, None)])
add("CAH", ["Cardinal Health", "Cardinal"], [("CAH", None, None)],
    not_after=r"^\s*(?:Ethanol|Bank|Bankshares|Glass|Logistics|Energy|Resources|Financial|Health\s+Partners|Innovations|Point|Infrastructure|Gas|Ventures|Capital|Minerals|Midstream)")
add("COR", ["AmerisourceBergen", "Amerisource Bergen", "AmerisourceBergen Drug", "Cencora"], [("COR", None, None)])
add("UNH", ["UnitedHealth", "UnitedHealthcare", "United Healthcare", "Optum", "OptumRx"], [("UNH", None, None)])
add("ELV", ["Anthem", "WellPoint", "Elevance"], [("ELV", None, None)])
add("HUM", ["Humana"], [("HUM", None, None)])
add("CI", ["Cigna", "Evernorth"], [("CI", None, None)])
add("CI_ESRX", ["Express Scripts", "Accredo", "Medco"], [("CI", "2019-01-01", None)])  # pre-merger ESRX: no Yahoo series
add("AET", ["Aetna"], [("AET", None, "2018-11-01")])
add("CNC", ["Centene"], [("CNC", None, None)])
add("MOH", ["Molina"], [("MOH", None, None)])
add("HCA", ["HCA Healthcare", "HCA"], [("HCA", None, None)])
add("HSIC", ["Henry Schein"], [("HSIC", None, None)])
add("PDCO", ["Patterson Companies", "Patterson Dental"], [("PDCO", None, "2025-04-01")])
add("OMI", ["Owens & Minor", "Owens and Minor"], [("OMI", None, None)])

# ------------------------------------------------------------------ defense / aerospace / industrial
add("BA", ["Boeing"], [("BA", None, None)])
add("LMT", ["Lockheed Martin", "Lockheed"], [("LMT", None, None)])
add("RTX", ["Raytheon Technologies", "RTX", "United Technologies", "Pratt & Whitney", "Pratt and Whitney",
            "Collins Aerospace", "UTC Aerospace", "Hamilton Sundstrand"], [("RTX", None, None)])  # RTX series = UTC history
add("RTX_RTN", ["Raytheon"], [("RTX", "2020-05-01", None)])  # Raytheon Co (RTN) pre-merger: no Yahoo series
add("GD", ["General Dynamics", "Gulfstream"], [("GD", None, None)])
add("NOC", ["Northrop Grumman", "Northrop"], [("NOC", None, None)])
add("LHX", ["L3Harris", "L3 Harris", "Harris Corporation"], [("LHX", None, None)])  # LHX series = Harris history
add("LHX_LLL", ["L-3 Communications", "L-3", "L3 Technologies"], [("LHX", "2019-08-01", None)])
add("HII", ["Huntington Ingalls"], [("HII", None, None)])
add("TXT", ["Textron", "Bell Helicopter"], [("TXT", None, None)])
add("SIKORSKY", ["Sikorsky"], [("RTX", None, "2015-10-01"), ("LMT", "2015-11-01", None)])
add("GE", ["General Electric", "GE Aviation", "GE Aerospace"], [("GE", None, None)])
add("GEHC", ["GE Healthcare", "GE HealthCare"], [("GE", None, "2022-12-01"), ("GEHC", "2023-01-01", None)])
add("GEV", ["GE Vernova"], [("GEV", "2024-04-01", None)])
add("HON", ["Honeywell"], [("HON", None, None)])
add("MMM", ["3M"], [("MMM", None, None)])
add("CAT", ["Caterpillar"], [("CAT", None, None)])
add("DE", ["Deere", "John Deere"], [("DE", None, None)])
add("CNH", ["CNH Industrial", "CNH"], [("CNH", None, None)])
add("AGCO", ["AGCO"], [("AGCO", None, None)])
add("PCAR", ["PACCAR"], [("PCAR", None, None)])
add("CMI", ["Cummins"], [("CMI", None, None)])
add("NAV", ["Navistar"], [("NAV", None, "2021-07-01")])
add("SPR", ["Spirit AeroSystems", "Spirit Aerosystems"], [("SPR", None, "2025-11-01")])
add("EMR", ["Emerson Electric", "Emerson"], [("EMR", None, None)])
add("WHR", ["Whirlpool"], [("WHR", None, None)])
add("ERJ", ["Embraer"], [("EMBJ", None, None)])
add("OSK", ["Oshkosh"], [("OSK", None, None)])

# ------------------------------------------------------------------ autos
add("GM", ["General Motors", "GM"], [("GM", "2010-12-01", None)])
add("F", ["Ford Motor", "Ford"], [("F", None, None)],
    not_after=r"^\s*(?:Foundation)")
add("STLA", ["Stellantis", "Fiat Chrysler", "FCA US", "FCA", "Chrysler"], [("STLA", "2014-11-01", None)])  # Chrysler pre-FCA listing: not US-listed
add("TSLA", ["Tesla"], [("TSLA", None, None)])
add("TM", ["Toyota"], [("TM", None, None)])
add("HMC", ["Honda"], [("HMC", None, None)])
add("HOG", ["Harley-Davidson", "Harley Davidson"], [("HOG", None, None)])
add("PII", ["Polaris"], [("PII", None, None)])
add("RIVN", ["Rivian"], [("RIVN", None, None)])

# ------------------------------------------------------------------ technology
add("AAPL", ["Apple"], [("AAPL", None, None)],
    not_after=r"^\s*(?:Hospitality|REIT|Leisure|Vacations|Bank|Rush|American)", not_before=r"(?:Big|Pink)\s$")
add("MSFT", ["Microsoft"], [("MSFT", None, None)])
add("GOOGL", ["Google", "Alphabet", "YouTube"], [("GOOGL", None, None)])
add("META", ["Facebook", "Meta Platforms"], [("META", None, None)])
add("INTC", ["Intel"], [("INTC", None, None)])
add("CSCO", ["Cisco"], [("CSCO", None, None)])
add("IBM", ["IBM", "International Business Machines"], [("IBM", None, None)])
add("HPQ", ["Hewlett-Packard", "Hewlett Packard", "HP Inc", "HP"], [("HPQ", None, None)],
    not_after=r"^\s*(?:Enterprise|E\b)")
add("HPE", ["Hewlett Packard Enterprise", "Hewlett-Packard Enterprise", "HPE"], [("HPE", "2015-11-01", None)])
add("DELL", ["Dell", "Dell Technologies", "Dell EMC", "EMC Corporation", "EMC Corp"], [("DELL", "2016-09-01", None)])  # Dell Inc (to 2013) and EMC (to 2016): no Yahoo series
add("ORCL", ["Oracle"], [("ORCL", None, None)])
add("QCOM", ["Qualcomm", "QUALCOMM"], [("QCOM", None, None)])
add("AVGO", ["Broadcom", "Avago"], [("AVGO", None, None)])
add("TXN", ["Texas Instruments"], [("TXN", None, None)])
add("MU", ["Micron"], [("MU", None, None)])
add("NVDA", ["Nvidia", "NVIDIA"], [("NVDA", None, None)])
add("AMD", ["Advanced Micro Devices", "AMD"], [("AMD", None, None)])
add("AMAT", ["Applied Materials"], [("AMAT", None, None)])
add("LRCX", ["Lam Research"], [("LRCX", None, None)])
add("KLAC", ["KLA-Tencor", "KLA Corporation", "KLA"], [("KLAC", None, None)])
add("ASML", ["ASML"], [("ASML", None, None)])
add("TSM", ["Taiwan Semiconductor", "TSMC"], [("TSM", None, None)])
add("STX", ["Seagate"], [("STX", None, None)])
add("WDC", ["Western Digital"], [("WDC", None, None)])
add("MSI", ["Motorola Solutions", "Motorola"], [("MSI", None, None)],
    not_after=r"^\s*(?:Mobility)")
add("NOK", ["Nokia"], [("NOK", None, None)])
add("ERIC", ["Ericsson"], [("ERIC", None, None)])
add("SONY", ["Sony"], [("SONY", None, None)])
add("FLEX", ["Flextronics", "Flex Ltd"], [("FLEX", None, None)])
add("JBL", ["Jabil"], [("JBL", None, None)])
add("SANM", ["Sanmina"], [("SANM", None, None)])
add("CLS", ["Celestica"], [("CLS", None, None)])
add("ARW", ["Arrow Electronics"], [("ARW", None, None)])
add("AVT", ["Avnet"], [("AVT", None, None)])
add("SNX", ["SYNNEX", "Synnex", "TD SYNNEX", "TD Synnex"], [("SNX", None, None)])
add("INGM", ["Ingram Micro"], [("INGM", "2024-11-01", None)])
add("TECD", ["Tech Data"], [("TECD", None, "2020-06-01")])
add("JNPR", ["Juniper Networks"], [("JNPR", None, "2025-07-01")])
add("NTAP", ["NetApp"], [("NTAP", None, None)])
add("CDW", ["CDW"], [("CDW", None, None)])

# ------------------------------------------------------------------ telecom / media
add("T", ["AT&T", "AT T"], [("T", None, None)])
add("T_DTV", ["DirecTV", "DIRECTV"], [("T", "2015-08-01", "2021-07-01")])  # DirecTV (DTV) pre-2015: no Yahoo series
add("VZ", ["Verizon", "Cellco"], [("VZ", None, None)])
add("TMUS", ["T-Mobile", "T Mobile"], [("TMUS", "2013-05-01", None)])  # TMUS series pre-2013 is MetroPCS
add("TMUS_PCS", ["MetroPCS", "Metro PCS"], [("TMUS", None, None)])
add("S", ["Sprint"], [("S", None, "2020-04-01")])
add("CMCSA", ["Comcast", "NBCUniversal", "NBC Universal"], [("CMCSA", None, None)])
add("CHTR", ["Charter Communications"], [("CHTR", None, None)])
add("CHTR_TWC", ["Time Warner Cable"], [("CHTR", "2016-06-01", None)])
add("SATS", ["EchoStar"], [("SATS", None, None)])
add("SATS_DISH", ["DISH Network", "Dish Network"], [("SATS", "2024-01-01", None)])
add("DIS", ["Walt Disney", "Disney"], [("DIS", None, None)])
add("NFLX", ["Netflix"], [("NFLX", None, None)])
add("LUMN", ["CenturyLink", "Lumen Technologies"], [("LUMN", None, None)])

# ------------------------------------------------------------------ consumer / food / pharma
add("PG", ["Procter & Gamble", "Procter and Gamble", "P&G"], [("PG", None, None)])
add("PEP", ["PepsiCo", "Pepsi Bottling", "Pepsi"], [("PEP", None, None)])
add("KO", ["Coca-Cola Company", "The Coca-Cola Company", "Coca Cola Company"], [("KO", None, None)])
add("KDP", ["Keurig Dr Pepper", "Dr Pepper Snapple"], [("KDP", None, None)])
add("NKE", ["Nike", "NIKE"], [("NKE", None, None)])
add("MCD", ["McDonald's", "McDonalds"], [("MCD", None, None)])
add("SBUX", ["Starbucks"], [("SBUX", None, None)])
add("YUM", ["Yum! Brands", "Yum Brands"], [("YUM", None, None)])
add("PM", ["Philip Morris"], [("PM", None, None)])
add("MO", ["Altria"], [("MO", None, None)])
add("PFE", ["Pfizer"], [("PFE", None, None)])
add("MRK", ["Merck"], [("MRK", None, None)], not_after=r"^\s*(?:KGaA|Serono)")
add("JNJ", ["Johnson & Johnson", "Johnson and Johnson", "Janssen", "Ethicon", "DePuy"], [("JNJ", None, None)])
add("ABT", ["Abbott Laboratories", "Abbott"], [("ABT", None, None)])
add("ABBV", ["AbbVie"], [("ABBV", None, None)])
add("BMY", ["Bristol-Myers Squibb", "Bristol Myers Squibb", "Bristol-Myers"], [("BMY", None, None)])
add("BMY_CELG", ["Celgene"], [("BMY", "2019-12-01", None)])
add("LLY", ["Eli Lilly", "Lilly"], [("LLY", None, None)])
add("AMGN", ["Amgen"], [("AMGN", None, None)])
add("GILD", ["Gilead"], [("GILD", None, None)])
add("BIIB", ["Biogen"], [("BIIB", None, None)])
add("MDT", ["Medtronic"], [("MDT", None, None)])
add("BAX", ["Baxter"], [("BAX", None, None)])
add("NVS", ["Novartis"], [("NVS", None, None)])
add("SNY", ["Sanofi"], [("SNY", None, None)])
add("GSK", ["GlaxoSmithKline", "GSK"], [("GSK", None, None)])
add("AZN", ["AstraZeneca"], [("AZN", None, None)])
add("TAK", ["Takeda"], [("TAK", None, None)])
add("NVO", ["Novo Nordisk"], [("NVO", None, None)])
add("TEVA", ["Teva"], [("TEVA", None, None)])
add("VTRS", ["Mylan", "Viatris"], [("VTRS", None, None)])

# ------------------------------------------------------------------ energy purchasers and customers
add("XOM", ["ExxonMobil", "Exxon Mobil", "Exxon"], [("XOM", None, None)])
add("XOM_XTO", ["XTO Energy"], [("XOM", "2010-07-01", None)])
add("CVX", ["Chevron"], [("CVX", None, None)])
add("SHEL", ["Shell"], [("SHEL", None, None)], not_after=r"^\s*(?:company|companies|corporation|entity|entities)\b")
add("BP", ["BP America", "BP Products", "BP Energy", "BP p.l.c", "BP plc", "BP"], [("BP", None, None)])
add("COP", ["ConocoPhillips"], [("COP", None, None)])
add("PSX", ["Phillips 66"], [("PSX", None, None)])
add("VLO", ["Valero"], [("VLO", None, None)])
add("MPC", ["Marathon Petroleum", "MPLX"], [("MPC", None, None)])
add("OXY", ["Occidental"], [("OXY", None, None)])
add("PAA", ["Plains Marketing", "Plains All American", "Plains Pipeline", "Plains LPG"], [("PAA", None, None)])
add("EPD", ["Enterprise Products", "Enterprise Crude"], [("EPD", None, None)])
add("ET", ["Energy Transfer"], [("ET", None, None)])
add("KMI", ["Kinder Morgan"], [("KMI", None, None)])
add("WMB", ["Williams Partners", "Williams Companies"], [("WMB", None, None)])
add("OKE", ["ONEOK"], [("OKE", None, None)])
add("TRGP", ["Targa"], [("TRGP", None, None)])
add("ENB", ["Enbridge"], [("ENB", None, None)])
add("DINO", ["HollyFrontier", "Holly Frontier", "HF Sinclair", "Holly Refining"], [("DINO", None, None)])
add("DK", ["Delek"], [("DK", None, None)])
add("SLB", ["Schlumberger", "SLB"], [("SLB", None, None)])
add("HAL", ["Halliburton"], [("HAL", None, None)])
add("BKR", ["Baker Hughes"], [("BKR", None, None)])
add("LNG", ["Cheniere"], [("LNG", None, None)])
add("EOG", ["EOG Resources"], [("EOG", None, None)])
add("DVN", ["Devon Energy"], [("DVN", None, None)])
add("APA", ["Apache Corporation"], [("APA", None, None)])
add("CHK", ["Chesapeake Energy"], [("EXE", None, None)])

# ------------------------------------------------------------------ logistics
add("FDX", ["FedEx"], [("FDX", None, None)])
add("UPS", ["United Parcel Service", "UPS"], [("UPS", None, None)])

# ------------------------------------------------------------------ added from the discovery sample
# (data/discovery_names.csv) and other frequently named large US-listed companies
add("MUSA", ["Murphy USA"], [("MUSA", None, None)])
add("DVA", ["DaVita"], [("DVA", None, None)])
add("SYK", ["Stryker"], [("SYK", None, None)])
add("BHP", ["BHP Billiton", "BHP"], [("BHP", None, None)])
add("WFC", ["Wells Fargo"], [("WFC", None, None)])
add("JPM", ["JPMorgan Chase", "JPMorgan", "JP Morgan", "J.P. Morgan"], [("JPM", None, None)])
add("BAC", ["Bank of America"], [("BAC", None, None)])
add("C", ["Citigroup", "Citibank"], [("C", None, None)])
add("AXP", ["American Express"], [("AXP", None, None)])
add("V", ["Visa Inc", "Visa U.S.A", "Visa USA"], [("V", None, None)])
add("MA", ["MasterCard", "Mastercard"], [("MA", None, None)])
add("PYPL", ["PayPal"], [("PYPL", "2015-08-01", None)])
add("FMS", ["Fresenius Medical Care", "Fresenius"], [("FMS", None, None)], not_after=r"^\s*(?:Kabi)")
add("AR", ["Antero Resources", "Antero"], [("AR", None, None)], not_after=r"^\s*(?:Midstream)")
add("FSLR", ["First Solar"], [("FSLR", None, None)])
add("LZB", ["La-Z-Boy"], [("LZB", None, None)])
add("DOW", ["Dow Inc", "Dow Chemical", "The Dow Chemical Company"], [("DOW", "2019-05-01", None)])  # Dow Inc listed 2019
add("DD", ["DuPont", "E. I. du Pont", "E.I. du Pont"], [("DD", None, None)])
add("EIX", ["Southern California Edison", "Edison International"], [("EIX", None, None)])
add("BB", ["BlackBerry", "Research In Motion"], [("BB", None, None)])
add("CIEN", ["Ciena"], [("CIEN", None, None)])
add("GLW", ["Corning Incorporated", "Corning Inc"], [("GLW", None, None)])
add("GRMN", ["Garmin"], [("GRMN", None, None)])
add("LOGI", ["Logitech"], [("LOGI", None, None)])
add("ADI", ["Analog Devices"], [("ADI", None, None)])
add("MRVL", ["Marvell"], [("MRVL", None, None)])
add("NXPI", ["NXP Semiconductors", "NXP"], [("NXPI", None, None)])
add("STM", ["STMicroelectronics"], [("STM", None, None)])
add("ON", ["ON Semiconductor", "onsemi"], [("ON", None, None)])
add("SWKS", ["Skyworks"], [("SWKS", None, None)])
add("QRVO", ["Qorvo"], [("QRVO", None, None)])
add("MCHP", ["Microchip Technology"], [("MCHP", None, None)])
add("CRM", ["Salesforce"], [("CRM", None, None)])
add("ADBE", ["Adobe"], [("ADBE", None, None)])
add("ACN", ["Accenture"], [("ACN", None, None)])
add("UBER", ["Uber Technologies", "Uber"], [("UBER", None, None)])
add("ROKU", ["Roku"], [("ROKU", None, None)])
add("BIDU", ["Baidu"], [("BIDU", None, None)])
add("BABA", ["Alibaba"], [("BABA", None, None)])
add("JD", ["JD.com"], [("JD", None, None)])
add("SHOP", ["Shopify"], [("SHOP", None, None)])
add("PHG", ["Koninklijke Philips", "Philips"], [("PHG", None, None)], not_before=r"(?i)conoco[\s\-]?$")
add("RCI", ["Rogers Communications"], [("RCI", None, None)])
add("BCE", ["Bell Canada", "BCE Inc"], [("BCE", None, None)])
add("TU", ["TELUS", "Telus"], [("TU", None, None)])
add("KMB", ["Kimberly-Clark", "Kimberly Clark"], [("KMB", None, None)])
add("CL", ["Colgate-Palmolive", "Colgate"], [("CL", None, None)])
add("CLX", ["Clorox"], [("CLX", None, None)])
add("UL", ["Unilever"], [("UL", None, None)])
add("KHC", ["Kraft Heinz"], [("KHC", "2015-08-01", None)])
add("MDLZ", ["Mondelez", "Kraft Foods Inc", "Kraft Foods, Inc"], [("MDLZ", None, None)])
add("GIS", ["General Mills"], [("GIS", None, None)])
add("CAG", ["ConAgra", "Conagra"], [("CAG", None, None)])
add("TSN", ["Tyson Foods", "Tyson"], [("TSN", None, None)])
add("HSY", ["Hershey"], [("HSY", None, None)])
add("CPB", ["Campbell Soup", "Campbell's"], [("CPB", None, None)])
add("SJM", ["J.M. Smucker", "Smucker"], [("SJM", None, None)])
add("HRL", ["Hormel"], [("HRL", None, None)])
add("BUD", ["Anheuser-Busch", "AB InBev", "Anheuser Busch"], [("BUD", None, None)])
add("TAP", ["Molson Coors", "MillerCoors"], [("TAP", None, None)])
add("STZ", ["Constellation Brands"], [("STZ", None, None)])
add("DEO", ["Diageo"], [("DEO", None, None)])
add("EL", ["Estee Lauder", "Estée Lauder"], [("EL", None, None)])
add("MAT", ["Mattel"], [("MAT", None, None)])
add("HAS", ["Hasbro"], [("HAS", None, None)])
add("VFC", ["VF Corporation", "V.F. Corporation"], [("VFC", None, None)])
add("PVH", ["PVH Corp", "Phillips-Van Heusen"], [("PVH", None, None)])
add("RL", ["Ralph Lauren", "Polo Ralph Lauren"], [("RL", None, None)])
add("GAP", ["Gap Inc", "The Gap"], [("GAP", None, None)])
add("UAA", ["Under Armour"], [("UAA", None, None)])
add("LEN", ["Lennar"], [("LEN", None, None)])
add("DHI", ["D.R. Horton", "DR Horton"], [("DHI", None, None)])
add("PHM", ["PulteGroup", "Pulte Homes"], [("PHM", None, None)])
add("NVR", ["NVR, Inc", "NVR Inc"], [("NVR", None, None)])
add("TOL", ["Toll Brothers"], [("TOL", None, None)])
add("MAS", ["Masco"], [("MAS", None, None)])
add("MHK", ["Mohawk Industries"], [("MHK", None, None)])
add("CARR", ["Carrier Global", "Carrier Corporation"], [("CARR", "2020-04-01", None)])
add("TT", ["Trane Technologies", "Trane"], [("TT", None, None)])
add("TT_IR", ["Ingersoll-Rand", "Ingersoll Rand"], [("TT", None, "2020-02-01"), ("IR", "2020-03-01", None)])
add("LII", ["Lennox"], [("LII", None, None)])
add("JCI", ["Johnson Controls"], [("JCI", None, None)])
add("ETN", ["Eaton"], [("ETN", None, None)], not_after=r"^\s*(?:Vance)")
add("PH", ["Parker Hannifin", "Parker-Hannifin"], [("PH", None, None)])
add("ITW", ["Illinois Tool Works"], [("ITW", None, None)])
add("ROK", ["Rockwell Automation"], [("ROK", None, None)])
add("DHR", ["Danaher"], [("DHR", None, None)])
add("TMO", ["Thermo Fisher"], [("TMO", None, None)])
add("ZBH", ["Zimmer Biomet", "Zimmer"], [("ZBH", None, None)])
add("BSX", ["Boston Scientific"], [("BSX", None, None)])
add("BDX", ["Becton Dickinson", "Becton, Dickinson"], [("BDX", None, None)])
add("DGX", ["Quest Diagnostics"], [("DGX", None, None)])
add("LH", ["LabCorp", "Laboratory Corporation of America"], [("LH", None, None)])
add("ILMN", ["Illumina"], [("ILMN", None, None)])
add("A", ["Agilent"], [("A", None, None)])
add("REGN", ["Regeneron"], [("REGN", None, None)])
add("VRTX", ["Vertex Pharmaceuticals"], [("VRTX", None, None)])
add("GRFS", ["Grifols"], [("GRFS", None, None)])
add("THC", ["Tenet Healthcare"], [("THC", None, None)])
add("CYH", ["Community Health Systems"], [("CYH", None, None)])
add("UHS", ["Universal Health Services"], [("UHS", None, None)])
add("UNP", ["Union Pacific"], [("UNP", None, None)])
add("CSX", ["CSX"], [("CSX", None, None)])
add("NSC", ["Norfolk Southern"], [("NSC", None, None)])
add("DAL", ["Delta Air Lines", "Delta Airlines"], [("DAL", None, None)])
add("AAL", ["American Airlines"], [("AAL", None, None)])
add("UAL", ["United Airlines", "United Continental"], [("UAL", None, None)])
add("LUV", ["Southwest Airlines"], [("LUV", None, None)])
add("ALK", ["Alaska Airlines", "Alaska Air"], [("ALK", None, None)])
add("JBLU", ["JetBlue"], [("JBLU", None, None)])
add("JBHT", ["J.B. Hunt", "JB Hunt"], [("JBHT", None, None)])
add("SO", ["Southern Company", "Georgia Power", "Alabama Power", "Mississippi Power", "Southern Company Services"], [("SO", None, None)])
add("DUK", ["Duke Energy"], [("DUK", None, None)])
add("DUK_PGN", ["Progress Energy"], [("DUK", "2012-08-01", None)])
add("AEP", ["American Electric Power", "Appalachian Power"], [("AEP", None, None)])
add("D", ["Dominion Energy", "Dominion Resources", "Virginia Electric and Power", "Dominion Virginia Power"], [("D", None, None)])
add("NEE", ["NextEra", "Florida Power & Light", "Florida Power and Light", "FPL"], [("NEE", None, None)])
add("EXC", ["Exelon", "Commonwealth Edison", "ComEd", "PECO Energy", "Baltimore Gas and Electric"], [("EXC", None, None)])
add("PCG", ["Pacific Gas and Electric", "Pacific Gas & Electric", "PG&E"], [("PCG", None, None)])
add("SRE", ["Sempra", "San Diego Gas & Electric", "San Diego Gas and Electric", "Southern California Gas"], [("SRE", None, None)])
add("ED", ["Consolidated Edison", "Con Edison"], [("ED", None, None)])
add("PEG", ["Public Service Electric and Gas", "PSE&G"], [("PEG", None, None)])
add("XEL", ["Xcel Energy", "Northern States Power", "Public Service Company of Colorado"], [("XEL", None, None)])
add("ETR", ["Entergy"], [("ETR", None, None)])
add("FE", ["FirstEnergy"], [("FE", None, None)])
add("PPL", ["PPL Electric", "PPL Corporation", "Louisville Gas and Electric", "Kentucky Utilities"], [("PPL", None, None)])
add("AEE", ["Ameren"], [("AEE", None, None)])
add("DTE", ["DTE Energy", "Detroit Edison"], [("DTE", None, None)])
add("CMS", ["Consumers Energy", "CMS Energy"], [("CMS", None, None)])
add("CNP", ["CenterPoint"], [("CNP", None, None)])
add("VST", ["Vistra", "Luminant"], [("VST", None, None)])
add("NRG", ["NRG Energy"], [("NRG", None, None)])
add("EQT", ["EQT Corporation", "EQT Production", "EQT Energy"], [("EQT", None, None)])
add("RRC", ["Range Resources"], [("RRC", None, None)])
add("CTRA", ["Coterra", "Cabot Oil & Gas", "Cabot Oil and Gas"], [("CTRA", None, None)])
add("FANG", ["Diamondback Energy"], [("FANG", None, None)])
add("OVV", ["Ovintiv", "Encana"], [("OVV", None, None)])
add("MUR", ["Murphy Oil"], [("MUR", None, None)])
add("MRO", ["Marathon Oil"], [("MRO", None, "2024-10-01")])
add("HES", ["Hess Corporation"], [("HES", None, "2025-06-01")])
add("PXD", ["Pioneer Natural Resources"], [("PXD", None, "2024-04-01")])
add("NOV", ["National Oilwell Varco", "NOV Inc"], [("NOV", None, None)])
add("WES", ["Western Midstream", "Western Gas Partners"], [("WES", None, None)])
add("MPLX_", [], [])
add("SUN", ["Sunoco LP"], [("SUN", "2014-11-01", None)])
add("VNOM_", [], [])
add("NUE", ["Nucor"], [("NUE", None, None)])
add("STLD", ["Steel Dynamics"], [("STLD", None, None)])
add("X", ["United States Steel", "U.S. Steel"], [("X", None, None)])
add("CLF", ["Cleveland-Cliffs", "Cliffs Natural Resources"], [("CLF", None, None)])
add("CLF_AMUSA", ["ArcelorMittal USA"], [("MT", None, "2020-11-01"), ("CLF", "2020-12-01", None)])
add("MT", ["ArcelorMittal"], [("MT", None, None)], not_after=r"^\s*(?:USA)")
add("AA", ["Alcoa"], [("HWM", None, "2016-10-01"), ("AA", "2016-11-01", None)])  # HWM series = old Alcoa Inc
add("IP", ["International Paper"], [("IP", None, None)])
add("WRK", ["WestRock"], [("SW", None, None)])
add("LIN", ["Linde", "Praxair"], [("LIN", None, None)])
add("APD", ["Air Products"], [("APD", None, None)])
add("LYB", ["LyondellBasell"], [("LYB", None, None)])
add("PPG", ["PPG Industries"], [("PPG", None, None)])
add("SHW", ["Sherwin-Williams", "Sherwin Williams"], [("SHW", None, None)])
add("MLM", ["Martin Marietta"], [("MLM", None, None)])
add("VMC", ["Vulcan Materials"], [("VMC", None, None)])
add("WM", ["Waste Management"], [("WM", None, None)])
add("RSG", ["Republic Services"], [("RSG", None, None)])
add("PWR", ["Quanta Services"], [("PWR", None, None)])
add("FLR", ["Fluor"], [("FLR", None, None)])
add("J", ["Jacobs Engineering", "Jacobs Solutions"], [("J", None, None)])
add("KBR", ["KBR"], [("KBR", None, None)])
add("LDOS", ["Leidos"], [("LDOS", None, None)])
add("SAIC", ["Science Applications International"], [("SAIC", None, None)])
add("BAH", ["Booz Allen"], [("BAH", None, None)])
add("CACI", ["CACI"], [("CACI", None, None)])
add("TDG", ["TransDigm"], [("TDG", None, None)])
add("HWM", ["Howmet", "Arconic"], [("HWM", None, None)])
add("BWA", ["BorgWarner"], [("BWA", None, None)])
add("APTV", ["Aptiv", "Delphi Automotive", "Delphi Corporation"], [("APTV", None, None)])
add("LEA", ["Lear Corporation"], [("LEA", None, None)])
add("MGA", ["Magna International", "Magna"], [("MGA", None, None)])
add("ALV", ["Autoliv"], [("ALV", None, None)])
add("GT", ["Goodyear"], [("GT", None, None)])
add("CNHI_", [], [])
add("LKQ", ["LKQ"], [("LKQ", None, None)])
add("GPC", ["Genuine Parts", "NAPA"], [("GPC", None, None)])
add("GWW", ["W.W. Grainger", "Grainger"], [("GWW", None, None)])
add("FAST", ["Fastenal"], [("FAST", None, None)])
add("WCC", ["WESCO", "Wesco"], [("WCC", None, None)])
add("CVNA_", [], [])
add("KMX", ["CarMax"], [("KMX", None, None)])
add("AN", ["AutoNation"], [("AN", None, None)])
add("MKL_", [], [])
add("DISCA_", [], [])
add("WBD", ["Warner Bros. Discovery", "Warner Bros Discovery", "Discovery Communications"], [("WBD", None, None)])
add("PARA", ["ViacomCBS", "Paramount Global", "CBS Corporation"], [("PARA", None, None)])
add("FOXA", ["Fox Corporation"], [("FOXA", "2019-03-01", None)])
add("SIRI", ["Sirius XM", "SiriusXM"], [("SIRI", None, None)])
add("LOW_", [], [])
add("MKC", ["McCormick"], [("MKC", None, None)])
add("KDP_", [], [])
add("SFM", ["Sprouts Farmers"], [("SFM", None, None)])
add("CASY", ["Casey's General"], [("CASY", None, None)])
add("WEN_", [], [])
add("DPZ", ["Domino's Pizza"], [("DPZ", None, None)])
add("CMG", ["Chipotle"], [("CMG", None, None)])
add("DRI", ["Darden"], [("DRI", None, None)])
add("ARMK", ["Aramark"], [("ARMK", None, None)])
add("MAR", ["Marriott"], [("MAR", None, None)])
add("HLT", ["Hilton Worldwide", "Hilton Hotels"], [("HLT", None, None)])
add("CCL", ["Carnival Corporation", "Carnival Cruise"], [("CCL", None, None)])
add("RCL", ["Royal Caribbean"], [("RCL", None, None)])
add("LVS", ["Las Vegas Sands"], [("LVS", None, None)])
add("MGM", ["MGM Resorts", "MGM Mirage"], [("MGM", None, None)])
add("CZR", ["Caesars Entertainment"], [("CZR", "2020-07-01", None)])
add("TMUS2_", [], [])

# drop placeholder rows with no spellings
C = [c for c in C if c["spell"]]


# ---------------------------------------------------------------------------- regex
def _spell_re(s: str) -> str:
    """Escape a spelling; hyphens/spaces/apostrophes/periods interchangeable."""
    out = []
    for ch in s:
        if ch in "- ":
            out.append(r"[\s\-]?" if ch == "-" else r"[\s\-]+")
        elif ch == "'":
            out.append(r"['’]?\s?")
        elif ch == ".":
            out.append(r"\.?\s?")
        elif ch == "&":
            out.append(r"\s?(?:&|and)\s?")
        else:
            out.append(re.escape(ch))
    return "".join(out)


def compiled():
    """[(id, compiled regex, not_after, not_before)] longest spellings first."""
    out = []
    for c in C:
        sp = sorted(set(c["spell"]), key=len, reverse=True)
        pat = r"(?<![A-Za-z0-9&])(?:" + "|".join(_spell_re(s) for s in sp) + r")(?![A-Za-z0-9])"
        out.append((c["id"], re.compile(pat), re.compile(c["not_after"]) if c["not_after"] else None,
                    re.compile(c["not_before"]) if c["not_before"] else None))
    return out
