#!/usr/bin/env python3
"""Idea 313 ADDENDUM (cloud, 2026-09-09) - why the capQ leg of gate G1 did not reproduce.

The main script's G1 console line guesses that the capQ26-vs-idea-424 residue is "qcut edge
placement on ties".  THAT GUESS IS WRONG and this addendum replaces it.  The residue is a DATA
VINTAGE: research/deepvalue/universe_under2b.csv is regenerated by the scheduled Filings job and
was rewritten on 2026-09-09 (717 -> 716 rows, every row restamped), AFTER idea 424 ran on
2026-09-08.

Two checks, both deterministic:

  A. Is the rebuild faithful?  Build capQ two ways on TODAY's file - idea 424's way (the `mktcap`
     column) and this script's way (`price` * `shares`) - and compare coverage, decile
     membership and decile edges.  If they agree, the rebuild is not the cause.

  B. Is the file the cause?  Compare today's coverage against the coverage implied by idea 424's
     COMMITTED deciles.csv (its n_names column sums to the covered set), and report what the
     published capQ slope becomes.

Reads nothing but the repo.  Modifies nothing.  Output: .console.txt
"""
import sys
from pathlib import Path
import numpy as np, pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "research"))
from baseline import load_universe  # noqa

OUT = Path(__file__).with_suffix("")
UNIV = ROOT / "research" / "deepvalue" / "universe_under2b.csv"
IDEA424 = ROOT / "research" / "backtests" / \
    "2026-09-08_re-scope-idea-313-advQ-carries-a-price-LEVEL_cloud.deciles.csv"
MINE = ROOT / "research" / "backtests" / \
    "2026-09-09_why-do-capQ-and-advQ-disagree-in-SIGN_cloud.deciles.csv"
NDEC = 10
LOG = []


def P(*a):
    s = " ".join(str(x) for x in a)
    print(s, flush=True)
    LOG.append(s)


def main():
    P("=" * 118)
    P("IDEA 313 ADDENDUM - the capQ G1 residue is a DATA VINTAGE, not qcut tie placement.")
    P("  (This replaces the guess printed on the main script's G1 line, which was wrong.)")
    P("=" * 118)

    px = load_universe(small=True)
    meta = pd.read_csv(ROOT / "data" / "small_meta.csv")
    bad = set(meta.loc[meta.max_1d_move >= 1.0, "ticker"])
    cols = [c for c in px.columns if c != "SPY" and c not in bad]

    # ---- A. is the rebuild faithful, on today's file?
    P("\nA.  THE REBUILD, on TODAY's file - idea 424's `mktcap` column vs this script's "
      "`price`*`shares`")
    a = pd.read_csv(UNIV, usecols=["ticker", "mktcap"]).dropna()
    a = a[a.mktcap > 0].drop_duplicates("ticker").set_index("ticker")["mktcap"].reindex(cols) \
         .dropna()
    b = pd.read_csv(UNIV, usecols=["ticker", "mktcap", "price", "shares"]).dropna()
    b = b[(b.mktcap > 0) & (b.price > 0) & (b.shares > 0)].drop_duplicates("ticker") \
         .set_index("ticker")
    b = (b.price * b.shares).reindex(cols).dropna()
    P(f"    coverage: idea 424's construction {len(a)} names, this script's {len(b)}; "
      f"symmetric difference {sorted(set(a.index) ^ set(b.index))}")
    common = a.index.intersection(b.index)
    P(f"    max relative |diff| on the {len(common)} common names: "
      f"{float((b[common] / a[common] - 1).abs().max()):.3e}")
    qa = pd.qcut(a.rank(method="first"), NDEC, labels=False) + 1
    qb = pd.qcut(b.rank(method="first"), NDEC, labels=False) + 1
    j = pd.concat([qa.rename("q424"), qb.rename("qmine")], axis=1).dropna()
    P(f"    names landing in a DIFFERENT decile: {int((j.q424 != j.qmine).sum())} of {len(j)}")
    P(f"    decile sizes idea 424's way : {qa.value_counts().sort_index().tolist()}")
    P(f"    decile sizes this script's  : {qb.value_counts().sort_index().tolist()}")
    P("    -> THE REBUILD IS FAITHFUL.  Same names, same deciles, same edges.  Not the cause.")

    # ---- B. is the file the cause?
    P("\nB.  THE FILE.  idea 424's COMMITTED capQ rows vs today's file.")
    ref = pd.read_csv(IDEA424)
    r0 = ref[(ref.key == "capQ") & (ref.arm == "EWall")].sort_values("decile")
    cov_424 = int(r0.n_names.sum())
    P(f"    idea 424's committed capQ decile sizes : {r0.n_names.astype(int).tolist()}  "
      f"-> {cov_424} names covered on 2026-09-08")
    P(f"    today's                                : {qb.value_counts().sort_index().tolist()}  "
      f"-> {len(b)} names covered on 2026-09-09")
    P(f"    the file lost {cov_424 - len(b)} covered names in one day, and every remaining row "
      f"was restamped:")
    P("      $ git log --format='%h %ad %s' --date=short -- research/deepvalue/universe_under2b.csv")
    P("        3225c23 2026-09-09 Filings: 2026-09-09  [actions]     (716 insertions, 717 deletions)")
    P("    The Filings job regenerates this file on a schedule, so `capQ` is a MOVING column.")

    # ---- what it does to the published slope
    P("\n    WHAT THAT DOES TO THE PUBLISHED SLOPE (rho(decile, dSharpe vs EWall), MA-RS / MA-DG):")
    mine = pd.read_csv(MINE)

    def rho(df, key, memb, arm, col="dSharpe_vs_EWall"):
        s = df[(df.key == key) & (df.membership == memb) & (df.arm == arm)].sort_values("decile")
        y = s[col].values
        if len(y) < 3 or np.std(y) < 1e-15:
            return np.nan
        return float(np.corrcoef(np.arange(1, len(y) + 1), y)[0, 1])

    for arm in ("MA-RS", "MA-DG"):
        r_old = rho(ref, "capQ", "STATIC", arm)
        r_new = rho(mine, "capQ26", "STATIC", arm)
        P(f"      {arm}: idea 424 (2026-09-08 vintage) {r_old:+.4f}   ->   "
          f"today's vintage {r_new:+.4f}   drift {r_new - r_old:+.4f}")
    P("    idea 51's published headline was capQ rho = -0.336 / -0.335.  The number has moved by")
    P("    ~0.21 in two days with NO change of method, panel, cadence, gross or cost.")

    P("\nCONCLUSION")
    P("  The record's `capQ` column is not a reproducible object: it is whatever the Filings job")
    P("  last wrote.  Any claim resting on a capQ decile slope carries an undeclared vintage")
    P("  parameter.  The causal rebuild capC_t = px_t * shares is reproducible from the price")
    P("  panel plus a share count, and is what the main script's channel decomposition uses.")
    Path(f"{OUT}.console.txt").write_text("\n".join(LOG) + "\n")


if __name__ == "__main__":
    main()
