#!/usr/bin/env python3
"""Idea 124 — book-size floor for any quoted price (cloud lane, 2026-09-07).

Question, verbatim from QUEUE
-----------------------------
"idea 122 found that ALL 24 panel-axis and ALL 5 cost-axis sign failures in idea 94's price
list are the 5-name V1u book (16/41 admissible) while the 56-name EWall book is 47/48.
Derive the floor directly: price the same instruments on top-n books with n in {3,5,10,20,40,
all} and find the n at which the denominator's sign becomes stable.  The answer is a number
PROTOCOL can state instead of '~20 names'.  Max 2 params."

What is being measured.  Every drawdown price the project quotes has the form

    rate = (CAGR_ctl - CAGR_arm) / (|MaxDD_ctl| - |MaxDD_arm|)     pp CAGR per pp MaxDD

and idea 122 showed the DENOMINATOR's sign, not the ratio, is the fragile object.  Its
3-axis sign test is adopted here VERBATIM, with its own settings, so this run cannot pick
its own bar:

    D1 cost    dMaxDD > 0 at every rung in {0, 5, 10, 25} bps
    D2 window  dMaxDD > 0 in BOTH 2009-2016 and 2017-2026
    D3 panel   dMaxDD > 0 in at least tau of NDRAW = 40 name-subsample draws that delete a
               fraction q of the panel at random, signals recomputed on the sub-panel
    ADMISSIBLE = D1 and D2 and D3.

THE BOOK LADDER (the new axis).  One construction, one dial: TOPn holds the top n names of
idea 94's plain composite at GROSS/n each, so gross is 0.75 at every n and only the NAME
COUNT moves.  n in {3, 5, 10, 20, 40, ALL}; ALL is the equal-weight-everything book.
    n = 20  nests idea 94/122's TOP20 EXACTLY.
    n = ALL nests idea 94/122's EWall EXACTLY.
Both nestings are asserted in [0], and every resulting row is asserted against idea 122's
committed grid.csv / d3.csv.  V1u (idea 94's 5-name book: composite DIVIDED BY sqrt(vol20),
0.15 per name) is carried as a REFERENCE arm-set, not a rung of the ladder: TOP5 differs
from it only by the vol scaler, so the pair decomposes idea 122's V1u finding into "5 names"
versus "vol-scaled ranking" — a by-product the queue's question needs and cannot get from
the count ladder alone.

TUNED PARAMETERS: exactly two, both of the TEST and neither of any trading rule —
    n    the book size, {3, 5, 10, 20, 40, ALL}
    tau  the D3 sign-agreement threshold, {0.80, 0.90, 0.95, 1.00}
q is FIXED at 0.10, inherited verbatim from ideas 119/122 (their pre-registered headline),
and the drawn sub-panels are generated by consuming idea 122's rng in ITS order so that the
q = 0.10 draws are bit-for-bit its published draws.  Universe {56, 136} and cost rung
{10, 25} are REPORTED axes, not tuned choices; every point is printed and committed.

PRE-REGISTERED READINGS OF "the n at which the sign becomes stable" (both fixed before any
number was read, because a floor needs a stated criterion or it is chosen after the fact):
    R1  n*(1.00) = the smallest n on the ladder at which EVERY published row of that book is
                   admissible.
    R2  n*(0.90) = the smallest n at which the admissible share reaches 0.90.
    R3  MONOTONICITY — is the admissible share non-decreasing in n?  If it is not, "a floor"
        is the wrong object and PROTOCOL cannot state one; that is a reportable answer.

PRE-REGISTERED PREDICTIONS (written before any number below was read):
    P1  the admissible share rises monotonically with n and R1/R2 land between n = 10 and 20.
    P2  the panel axis (D3) is the binding one at small n; the cost axis (D1) is nearly free
        at every n on these large-cap panels.
    P3  TOP5 is materially MORE admissible than V1u at the same count, i.e. idea 122's V1u
        failures are partly the vol scaler and not purely the 5-name width.

Rule 8 (required): idea 94's own selector S1 — among the arms of a cell that bought >= 1.0 pp
of IS MaxDD, take the LOWEST IS rate — evaluated untouched on 2017-2026, run per rung of the
ladder, against the cell's control, RULES v2 (live), RULES v1 and SPY; and S2, the same
selector after the IS-ONLY sign screen (D1 on IS returns and D3 on IS-window draws; the OOS
window is never consulted).  Both KEEP paths are evaluated for every arm row.

SURVIVORSHIP: universe.json and universe_broad.json are current-constituent lists, so every
absolute level is optimistic.  This run reports within-cell differences and the STABILITY of
a sign, both far less exposed than levels — but a survivorship-free panel could still move
which rows pass.

Deterministic (seeded), standalone.  Imports research/baseline.py, idea 94's script and idea
122's script; modifies nothing.
"""
import importlib.util, os, sys, time
from pathlib import Path
import numpy as np, pandas as pd

RESUME = os.environ.get("RESUME") == "1"
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "research"))
from baseline import rules_v1_weights, rules_v2_weights                          # noqa
from engine import backtest, metrics                                             # noqa

BT = ROOT / "research" / "backtests"


def _load(stem, name):
    s = importlib.util.spec_from_file_location(name, BT / f"{stem}.py")
    m = importlib.util.module_from_spec(s); s.loader.exec_module(m)
    return m


H = _load("2026-09-04_drawdown-insurance-price-list_B", "i94")          # arms + simulator
C = _load("2026-09-05_price-denominator-sign-test_C", "i122")           # the sign test

SLUG = "2026-09-07_book-size-floor-for-any-quoted-price_cloud"
OUT = BT / SLUG
NS = [3, 5, 10, 20, 40, "ALL"]                     # tuned dial 1
TAUS = (0.80, 0.90, 0.95, 1.00)                    # tuned dial 2
Q_STAR = 0.10                                      # inherited from ideas 119/122, NOT tuned
COST_RUNGS = [0.0, 5.0, 10.0, 25.0]
PUB_COSTS = [10.0, 25.0]
NDRAW, DROP_FRACS, SEED = C.NDRAW, C.DROP_FRACS, C.SEED
IS_END, OOS_START = H.IS_END, H.OOS_START
ARMS = [(n, k, kw, sp) for (n, k, kw, sp) in H.arm_specs() if n != "control"]
UNIS = [("universe.json(56)", dict()), ("universe_broad.json", dict(broad=True))]
BOOKS = [f"TOP{n}" if n != "ALL" else "ALL" for n in NS] + ["V1u"]

pd.set_option("display.width", 250); pd.set_option("display.max_columns", 60)
pd.set_option("display.max_rows", 4000)


# ---------------------------------------------------------------- the book ladder
def ranks_for(px, S, gate, conv):
    """Composite rank frame a TOPn book needs.  Shared by every n, which is what makes the
    ladder cheap: only the `<= n` comparison and the GROSS/n weight change with n."""
    if conv == "rw" and gate is not None:
        return S["comp"].where(C.gmask_c(px, gate, S)).rank(axis=1, ascending=False)
    return S["comp"].rank(axis=1, ascending=False)


def rk_key(gate, conv):
    """Which rank frame a (gate, conv) variant needs: `rw` re-ranks inside the gate, `dg`
    ranks the ungated panel and then zeroes gated-out names."""
    return (gate, "rw") if (gate is not None and conv == "rw") else (None, "dg")


def rank_cache(px, S):
    """One rank frame per (gate, conv) key, reused by all six rungs of the ladder."""
    out = {(None, "dg"): ranks_for(px, S, None, "dg")}
    for g in H.GATES:
        out[(g, "rw")] = ranks_for(px, S, g, "rw")
    return out


def targets_n(px, n, S, gate=None, conv="dg", rkc=None):
    """TOPn: top n of idea 94's plain composite at GROSS/n each (gross 0.75 at every n).
    n = 'ALL' is idea 94's EWall.  `dg` zeroes gated-out names into CASH; `rw` rebuilds the
    book among gated-in names only.  n=20 nests TOP20 and n='ALL' nests EWall (asserted)."""
    rkc = rank_cache(px, S) if rkc is None else rkc
    g = None if gate is None else C.gmask_c(px, gate, S)
    if n == "ALL":
        e = (pd.DataFrame(1.0, index=px.index, columns=px.columns).where(px.notna(), 0.0)
             if (g is None or conv == "dg") else g.astype(float))
        W = H.GROSS * e.div(e.sum(axis=1).replace(0, np.nan), axis=0).fillna(0.0)
        return W if g is None else (W.where(g, 0.0) if conv == "dg" else W)
    W = (rkc[rk_key(gate, conv)] <= n).astype(float) * (H.GROSS / n)
    if g is None or conv == "rw":
        return W
    return W.where(g, 0.0)


def book_targets(px, book, S, gate, conv, rkc):
    """Dispatch: a TOPn/ALL rung of the ladder, or the V1u reference book (idea 94's)."""
    if book == "V1u":
        return C.targets_c(px, "V1u", S, gate, conv)
    return targets_n(px, "ALL" if book == "ALL" else int(book[3:]), S, gate, conv, rkc)


# ---------------------------------------------------------------- main grid (D1, D2)
def build_grid(uname, kw):
    px = H.load_universe(**kw)
    start = px.index[260]
    spy = px["SPY"].pct_change().fillna(0).loc[start:]
    bars = H.bars_of(spy)
    S = C.signals(px)
    rkc = rank_cache(px, S)

    print(f"\n{'='*150}\nUNIVERSE {uname}: {px.shape[1]} names, {px.index[0].date()} -> "
          f"{px.index[-1].date()} | eval from {start.date()} | IS <= {IS_END} | OOS >= {OOS_START}")
    ms = metrics(spy)
    print(f"    SPY CAGR {ms['CAGR']:.2%} Sharpe {ms['Sharpe']:.3f} MaxDD {ms['MaxDD']:.2%}")

    # ---- [0] nesting gates, before any new number is read
    worst = 0.0
    for gate in [None] + H.GATES:
        for conv in (("dg",) if gate is None else ("dg", "rw")):
            a = targets_n(px, 20, S, gate, conv, rkc).fillna(0.0)
            e = C.targets_c(px, "TOP20", S, gate, conv).fillna(0.0)
            worst = max(worst, float((a - e).abs().to_numpy().max()))
            a = targets_n(px, "ALL", S, gate, conv, rkc).fillna(0.0)
            e = C.targets_c(px, "EWall", S, gate, conv).fillna(0.0)
            worst = max(worst, float((a - e).abs().to_numpy().max()))
    print(f"    G1 [{uname}] TOPn(n=20) nests TOP20 and TOPn(ALL) nests EWall over all 11 "
          f"(gate, conv) variants: max|diff| {worst:.3e}")
    assert worst < 1e-15

    v1_net = {c: backtest(px, rules_v1_weights(px), cost_bps=c, freq=H.FREQ)["returns"].loc[start:]
              for c in PUB_COSTS}
    v2_net = {c: backtest(px, rules_v2_weights(px), cost_bps=c, freq=H.FREQ)["returns"].loc[start:]
              for c in PUB_COSTS}

    rets = {}
    t0 = time.time()
    for book in BOOKS:
        for name, kind, kwargs, (g, conv) in H.arm_specs():
            W = book_targets(px, book, S, g, conv, rkc)
            for c in COST_RUNGS:
                rets[(book, name, c)] = H.run(px, W, bps=c, **kwargs)["r"].loc[start:]
    print(f"    grid runs done ({time.time()-t0:.0f}s)")

    rows = []
    for book in BOOKS:
        for c in PUB_COSTS:
            rc = rets[(book, "control", c)]
            for name, kind, _, _ in ARMS:
                ra = rets[(book, name, c)]
                dc, dd, rate = C.dpair(rc, ra)
                rec = dict(uni=uname, book=book, n=("ALL" if book in ("ALL", "V1u") else book[3:]),
                           cost=c, arm=name, kind=kind, dCAGR=dc, dMaxDD=dd, rate=rate,
                           published=bool(np.isfinite(rate)))
                for cc in COST_RUNGS:                                    # D1
                    _, dd_c, _ = C.dpair(rets[(book, "control", cc)], rets[(book, name, cc)])
                    rec[f"dMaxDD@{cc:.0f}"] = dd_c
                    _, dd_ci, _ = C.dpair(C.win(rets[(book, "control", cc)], "IS"),
                                          C.win(rets[(book, name, cc)], "IS"))
                    rec[f"dMaxDD_IS@{cc:.0f}"] = dd_ci
                for w in ("IS", "OOS"):                                  # D2
                    dcw, ddw, rw_ = C.dpair(C.win(rc, w), C.win(ra, w))
                    rec[f"dCAGR_{w}"], rec[f"dMaxDD_{w}"], rec[f"rate_{w}"] = dcw, ddw, rw_
                ma_, mc_ = metrics(ra), metrics(rc)
                mg = H.margins(ra, bars)
                ah1, ah2 = H.halves(ra)
                rec.update(H1=ah1, H2=ah2, spy_H1=bars["s1"], spy_H2=bars["s2"],
                           spy_OOS=bars["soos"], spy_MaxDD=bars["sdd"], spy_CAGR=bars["scagr"],
                           m4b_H1=mg["H1"], m4b_H2=mg["H2"], m4b_OOS=mg["OOS"],
                           m4b_DD=mg["DD"], m4b_CAGR=mg["CAGR"],
                           CAGR=ma_["CAGR"], Sharpe=ma_["Sharpe"], MaxDD=ma_["MaxDD"],
                           OOS_Sharpe=metrics(ra.loc[OOS_START:])["Sharpe"],
                           OOS_CAGR=metrics(ra.loc[OOS_START:])["CAGR"],
                           OOS_MaxDD=metrics(ra.loc[OOS_START:])["MaxDD"],
                           IS_Sharpe=metrics(ra.loc[:IS_END])["Sharpe"],
                           ctl_MaxDD=mc_["MaxDD"], ctl_CAGR=mc_["CAGR"],
                           p4a_v1=H.pass4a(ra, v1_net[c]), p4a=H.pass4a(ra, v2_net[c]),
                           p4b=all(v > 0 for v in mg.values()),
                           f4b=",".join([k for k, v in mg.items() if not v > 0]) or "-")
                rows.append(rec)
    G = pd.DataFrame(rows)
    G["D1_pass"] = np.all([G[f"dMaxDD@{c:.0f}"] > 0 for c in COST_RUNGS], axis=0)
    G["D2_pass"] = (G.dMaxDD_IS > 0) & (G.dMaxDD_OOS > 0)
    G["D1_pass_IS_only"] = np.all([G[f"dMaxDD_IS@{c:.0f}"] > 0 for c in COST_RUNGS], axis=0)
    return px, start, S, rkc, spy, bars, v1_net, v2_net, rets, G


# ---------------------------------------------------------------- D3 bootstrap
def bootstrap(uname, px, start):
    """Name-subsample draws.  The rng is consumed in idea 122's EXACT order (all three of its
    q values, in its order, with its seed) so the q = 0.10 sub-panels are bit-for-bit its
    published draws; only q = 0.10 is evaluated here."""
    rng = np.random.default_rng(SEED)
    ncol = px.shape[1]
    out = []
    t0 = time.time()
    for q in DROP_FRACS:
        k = int(round(ncol * (1 - q)))
        for d in range(NDRAW):
            keep = sorted(rng.choice(ncol, size=k, replace=False))
            if q != Q_STAR:
                continue                                  # consume the rng, skip the work
            sub = px.iloc[:, keep]
            Ss = C.signals(sub)
            rkc = rank_cache(sub, Ss)
            for book in BOOKS:
                rc = H.run(sub, book_targets(sub, book, Ss, None, "dg", rkc),
                           bps=H.PCOST)["r"].loc[start:]
                for name, kind, kwargs, (g, conv) in ARMS:
                    ra = H.run(sub, book_targets(sub, book, Ss, g, conv, rkc),
                               bps=H.PCOST, **kwargs)["r"].loc[start:]
                    rec = dict(uni=uname, q=q, draw=d, book=book, arm=name)
                    for w in ("full", "IS", "OOS"):
                        dc, dd, rt = C.dpair(C.win(rc, w), C.win(ra, w))
                        rec[f"dCAGR_{w}"], rec[f"dMaxDD_{w}"], rec[f"rate_{w}"] = dc, dd, rt
                    out.append(rec)
            if (d + 1) % 10 == 0:
                print(f"    [{uname}] q={q:.2f}: {d+1}/{NDRAW} draws ({time.time()-t0:.0f}s)",
                      flush=True)
    return pd.DataFrame(out)


def d3_table(B):
    g = B.groupby(["uni", "q", "book", "arm"])
    return pd.DataFrame(dict(
        frac_pos_full=g.dMaxDD_full.apply(lambda s: float((s > 0).mean())),
        frac_pos_IS=g.dMaxDD_IS.apply(lambda s: float((s > 0).mean())),
        frac_pos_OOS=g.dMaxDD_OOS.apply(lambda s: float((s > 0).mean())),
        frac_priceable=g.rate_full.apply(lambda s: float(s.notna().mean())),
        rate_med=g.rate_full.median(), dMaxDD_med=g.dMaxDD_full.median(),
        dCAGR_med=g.dCAGR_full.median())).reset_index()


# ---------------------------------------------------------------- run
def main():
    print(f"=== {SLUG}")
    print(f"Ladder: TOPn at GROSS/{'n'} (gross {H.GROSS} at every n), n in {NS}; V1u carried "
          f"as a reference book.")
    print(f"Tuned (2): n and tau {TAUS}.  q FIXED at {Q_STAR} (inherited from ideas 119/122), "
          f"NDRAW {NDRAW}, seed {SEED}.")
    print(f"Reported axes: universe {[u for u, _ in UNIS]}, cost rung {PUB_COSTS} bps, "
          f"{len(ARMS)} treated arms.")

    gcsv, bcsv = OUT.with_suffix(".grid.csv"), OUT.with_suffix(".bootstrap.csv")
    # RESUME re-runs the (cheap) grid to rebuild the return paths the walk-forward needs and
    # reloads the (expensive) bootstrap draws from disk.  Every number below is still computed,
    # never read back from a summary.
    boot_cache = pd.read_csv(bcsv) if (RESUME and bcsv.exists()) else None

    Gs, Bs, ctx = [], [], {}
    for uname, kw in UNIS:
        px, start, S, rkc, spy, bars, v1_net, v2_net, rets, G = build_grid(uname, kw)
        Gs.append(G)
        ctx[uname] = dict(px=px, start=start, spy=spy, bars=bars, v1=v1_net, v2=v2_net, rets=rets)
        if boot_cache is not None:
            print(f"[boot] {uname}: reloaded from {bcsv.name}")
            Bs.append(boot_cache[boot_cache.uni == uname].copy())
            continue
        print(f"\n[boot] {uname}: q={Q_STAR}, {NDRAW} draws x {len(BOOKS)} books x "
              f"{len(ARMS)} arms")
        Bs.append(bootstrap(uname, px, start))
    G = pd.concat(Gs, ignore_index=True); B = pd.concat(Bs, ignore_index=True)
    D3 = d3_table(B)
    G.to_csv(OUT.with_suffix(".grid_raw.csv"), index=False)   # written BEFORE the gates so a
    B.to_csv(bcsv, index=False)                               # gate failure discards no work
    D3.to_csv(OUT.with_suffix(".d3.csv"), index=False)

    # ---- [0] reproduction of idea 122's committed numbers
    print("\n[0] REPRODUCTION GATES vs idea 122's committed CSVs")
    p122 = pd.read_csv(BT / "2026-09-05_price-denominator-sign-test_C.signtest.csv")
    m = {"TOP20": "TOP20", "ALL": "EWall", "V1u": "V1u"}
    worst = {}
    for mine, theirs in m.items():
        a = G[G.book == mine].set_index(["uni", "cost", "arm"]).sort_index()
        b = p122[p122.book == theirs].set_index(["uni", "cost", "arm"]).sort_index()
        cols = ["dCAGR", "dMaxDD", "dMaxDD_IS", "dMaxDD_OOS"] + [f"dMaxDD@{c:.0f}" for c in COST_RUNGS]
        w = max(float((a[c] - b[c]).abs().max()) for c in cols)
        worst[mine] = w
        print(f"    G2 grid {mine:>5} vs idea 122 {theirs:<5}: max|d| over {len(cols)} columns "
              f"x {len(a)} rows = {w:.3e}")
        assert w < 1e-12
    d122 = pd.read_csv(BT / "2026-09-05_price-denominator-sign-test_C.d3.csv")
    d122 = d122[np.isclose(d122.q, Q_STAR)]
    for mine, theirs in m.items():
        a = D3[D3.book == mine].set_index(["uni", "arm"]).sort_index()
        b = d122[d122.book == theirs].set_index(["uni", "arm"]).sort_index()
        w = max(float((a[c] - b[c]).abs().max()) for c in ("frac_pos_full", "frac_pos_IS",
                                                           "frac_pos_OOS", "frac_priceable"))
        print(f"    G3 D3 draws {mine:>5} vs idea 122 {theirs:<5} at q={Q_STAR}: max|d| {w:.3e} "
              f"({len(a)} arms) -> the sub-panels are its published draws")
        assert w < 1e-12

    # ---- assemble admissibility
    D3i = D3.set_index(["uni", "book", "arm"])
    for col, src in (("frac_full", "frac_pos_full"), ("frac_IS", "frac_pos_IS")):
        G[col] = [D3i.loc[(u, b, a), src] for u, b, a in zip(G.uni, G.book, G.arm)]
    for tau in TAUS:
        G[f"D3_{tau:.2f}"] = G.frac_full >= tau
        G[f"ADM_{tau:.2f}"] = G.D1_pass & G.D2_pass & G[f"D3_{tau:.2f}"]
        G[f"ADM_IS_{tau:.2f}"] = G.D1_pass_IS_only & (G.frac_IS >= tau)
    G.to_csv(gcsv, index=False); B.to_csv(bcsv, index=False)
    D3.to_csv(OUT.with_suffix(".d3.csv"), index=False)
    print(f"    wrote {gcsv.name} ({len(G)} rows), {bcsv.name} ({len(B)} rows), .d3.csv")

    W = walk_forward(G, ctx)
    W.to_csv(OUT.with_suffix(".walkforward.csv"), index=False)
    analyse(G, D3, W)


# ---------------------------------------------------------------- rule 8
def walk_forward(G, ctx):
    """S1 = idea 94's selector (lowest IS rate among arms buying >= 1.0 pp of IS MaxDD).
    S2 = the same after the IS-ONLY sign screen (D1 on IS returns, D3 on IS-window draws).
    The OOS window is never consulted by either screen."""
    out = []
    for (uname, book, c), cell in G.groupby(["uni", "book", "cost"]):
        cx = ctx[uname]
        rc = cx["rets"][(book, "control", c)]
        spy = cx["spy"]
        elig = cell[(cell.dMaxDD_IS >= 1.0) & np.isfinite(cell.rate_IS)]
        for sel, tau in [("S1", None)] + [("S2", t) for t in TAUS]:
            e = elig if sel == "S1" else elig[elig[f"ADM_IS_{tau:.2f}"]]
            if not len(e):
                out.append(dict(uni=uname, book=book, cost=c, sel=sel, tau=tau, arm="(none)",
                                n_elig=len(e)))
                continue
            pick = e.loc[e.rate_IS.idxmin()]
            ra = cx["rets"][(book, pick.arm, c)]
            mo, mco = metrics(ra.loc[OOS_START:]), metrics(rc.loc[OOS_START:])
            mv1, mv2 = metrics(cx["v1"][c].loc[OOS_START:]), metrics(cx["v2"][c].loc[OOS_START:])
            msp = metrics(spy.loc[OOS_START:])
            out.append(dict(uni=uname, book=book, cost=c, sel=sel, tau=tau, arm=pick.arm,
                            n_elig=len(e), IS_rate=pick.rate_IS,
                            OOS_Sharpe=mo["Sharpe"], OOS_CAGR=mo["CAGR"], OOS_MaxDD=mo["MaxDD"],
                            ctl_OOS_Sharpe=mco["Sharpe"], ctl_OOS_CAGR=mco["CAGR"],
                            ctl_OOS_MaxDD=mco["MaxDD"], v1_OOS_Sharpe=mv1["Sharpe"],
                            v2_OOS_Sharpe=mv2["Sharpe"], spy_OOS_Sharpe=msp["Sharpe"],
                            spy_OOS_CAGR=msp["CAGR"], spy_OOS_MaxDD=msp["MaxDD"],
                            OOS_rate=pick.rate_OOS, OOS_dMaxDD=pick.dMaxDD_OOS,
                            sign_held_OOS=bool(pick.dMaxDD_OOS > 0)))
    return pd.DataFrame(out)


# ---------------------------------------------------------------- analysis
def analyse(G, D3, W):
    order = [f"TOP{n}" if n != "ALL" else "ALL" for n in NS]
    pub = G[G.published]

    print("\n\n[A] THE PRICE LIST BY BOOK SIZE (published rows = finite rate at idea 94's "
          "0.10 pp floor)")
    print(f"     {'book':>6} {'rows':>5} {'published':>10} {'median rate':>12} "
          f"{'median dMaxDD':>14} {'median dCAGR':>13}")
    for b in order + ["V1u"]:
        z, zp = G[G.book == b], pub[pub.book == b]
        print(f"     {b:>6} {len(z):>5} {len(zp):>6}/{len(z):<3} {zp.rate.median():>12.3f} "
              f"{zp.dMaxDD.median():>14.2f} {zp.dCAGR.median():>13.2f}")

    print("\n\n[B] ADMISSIBLE SHARE BY BOOK SIZE — the queue's question")
    print("     Share of PUBLISHED rows passing all three axes (D1 cost, D2 window, D3 panel),")
    print(f"     pooled over both universes and both published rungs.  q = {Q_STAR}.")
    print(f"     {'book':>6} {'pub':>4} | " + " | ".join(f"tau={t:.2f}" for t in TAUS)
          + f" | {'D1 only':>8} {'D2 only':>8} {'D3(0.90)':>9}")
    share = {}
    for b in order + ["V1u"]:
        z = pub[pub.book == b]
        cells = []
        for t in TAUS:
            s = float(z[f"ADM_{t:.2f}"].mean()) if len(z) else np.nan
            share[(b, t)] = s
            cells.append(f"{s:>8.3f}")
        print(f"     {b:>6} {len(z):>4} | " + " | ".join(cells)
              + f" | {z.D1_pass.mean():>8.3f} {z.D2_pass.mean():>8.3f} "
                f"{z['D3_0.90'].mean():>9.3f}")

    print("\n     Per-axis FAILURE COUNTS among published rows (a row can fail more than one):")
    print(f"     {'book':>6} | {'D1 cost':>8} {'D2 window':>10} {'D3 panel@0.90':>14} "
          f"{'any':>5}")
    for b in order + ["V1u"]:
        z = pub[pub.book == b]
        print(f"     {b:>6} | {int((~z.D1_pass).sum()):>8} {int((~z.D2_pass).sum()):>10} "
              f"{int((~z['D3_0.90']).sum()):>14} {int((~z['ADM_0.90']).sum()):>5}")

    print("\n\n[B2] THE SAME LADDER, TWO ROBUSTNESS READINGS (headline tau = 0.90)")
    print("     The published denominator moves with n (idea 94's 0.10 pp floor admits a")
    print("     different number of rows per book), so the share is also read over ALL rows;")
    print("     and separately within each universe, to see whether the shape is one panel's.")
    print(f"     {'book':>6} | {'pub share':>10} {'ALL-rows share':>15} | "
          f"{'u56 pub':>9} {'broad pub':>10}")
    lad = {}
    for b in order + ["V1u"]:
        z, zp = G[G.book == b], pub[pub.book == b]
        u = zp[zp.uni == UNIS[0][0]], zp[zp.uni == UNIS[1][0]]
        lad[b] = (float(zp["ADM_0.90"].mean()), float(z["ADM_0.90"].mean()),
                  float(u[0]["ADM_0.90"].mean()), float(u[1]["ADM_0.90"].mean()))
        print(f"     {b:>6} | {lad[b][0]:>10.3f} {lad[b][1]:>15.3f} | {lad[b][2]:>9.3f} "
              f"{lad[b][3]:>10.3f}")
    nn = list(range(len(order)))
    for j, lab in ((0, "published"), (1, "all rows"), (2, "u56 pub"), (3, "broad pub")):
        v = [lad[b][j] for b in order]
        inv = sum(1 for i in range(len(v) - 1) if v[i] > v[i + 1] + 1e-12)
        rho = (pd.Series(nn).rank().corr(pd.Series(v).rank())
               if pd.Series(v).nunique() > 1 else float("nan"))
        print(f"     {lab:>10}: spearman(rung, share) {rho:+.3f}; "
              f"{inv} of {len(v)-1} ladder steps go DOWN -> "
              f"{'NOT monotone' if inv else 'monotone'}")

    print("\n\n[C] THE FLOOR: R1, R2 and R3 at each tau")
    print(f"     {'tau':>5} | {'R1 n*(share=1.00)':>18} | {'R2 n*(share>=0.90)':>19} | "
          f"{'R3 monotone in n?':>18} | shares along the ladder")
    for t in TAUS:
        vals = [share[(b, t)] for b in order]
        r1 = next((b for b, v in zip(order, vals) if v >= 1.0), None)
        r2 = next((b for b, v in zip(order, vals) if v >= 0.90), None)
        mono = all(vals[i] <= vals[i + 1] + 1e-12 for i in range(len(vals) - 1))
        print(f"     {t:>5.2f} | {str(r1):>18} | {str(r2):>19} | {str(mono):>18} | "
              + " ".join(f"{b}:{v:.2f}" for b, v in zip(order, vals)))
    print("     (R1/R2 report the FIRST rung of the ladder that clears the bar, reading "
          "n = 3 -> ALL;\n      'None' means no rung on the ladder clears it.)")

    print("\n\n[D] THE V1u DECOMPOSITION: is idea 122's finding the COUNT or the VOL SCALER?")
    print("     TOP5 and V1u hold 5 names at 0.15 each; they differ ONLY by the 1/sqrt(vol20)")
    print("     factor in the ranking.  Idea 122 published V1u at 16/41 admissible.")
    for t in TAUS:
        z5, zv = pub[pub.book == "TOP5"], pub[pub.book == "V1u"]
        print(f"     tau={t:.2f}:  TOP5 {int(z5[f'ADM_{t:.2f}'].sum())}/{len(z5)} "
              f"({share[('TOP5', t)]:.3f})   vs   V1u {int(zv[f'ADM_{t:.2f}'].sum())}/{len(zv)} "
              f"({share[('V1u', t)]:.3f})   gap {share[('TOP5', t)] - share[('V1u', t)]:+.3f}")

    print("\n\n[E] THE MECHANISM: what moves with n")
    print(f"     {'book':>6} {'ctl MaxDD':>10} {'ctl CAGR':>9} {'med |dMaxDD|':>13} "
          f"{'sd of dMaxDD over draws':>24} {'med frac_pos':>13}")
    for b in order + ["V1u"]:
        z = G[(G.book == b) & (G.cost == 10.0)]
        d = D3[D3.book == b]
        print(f"     {b:>6} {z.ctl_MaxDD.median():>10.2%} {z.ctl_CAGR.median():>9.2%} "
              f"{z.dMaxDD.abs().median():>13.2f} {'(see .bootstrap.csv)':>24} "
              f"{d.frac_pos_full.median():>13.3f}")

    print("\n\n[F] RULE 8 WALK-FORWARD (idea 94's S1 selector, and S2 after the IS-only screen)")
    print(f"     {'uni':>18} {'book':>6} {'c':>3} {'sel':>4} {'tau':>5} | {'arm':>20} "
          f"{'OOS Shrp':>9} {'OOS CAGR':>9} {'OOS MaxDD':>10} | {'ctl':>7} {'v2':>6} {'SPY':>6} "
          f"| sign held")
    for _, r in W.iterrows():
        if r.arm == "(none)":
            print(f"     {r.uni:>18} {r.book:>6} {r.cost:>3.0f} {r.sel:>4} "
                  f"{'-' if r.tau is None or pd.isna(r.tau) else f'{r.tau:.2f}':>5} | "
                  f"{'(no admissible arm)':>20}")
            continue
        print(f"     {r.uni:>18} {r.book:>6} {r.cost:>3.0f} {r.sel:>4} "
              f"{'-' if pd.isna(r.tau) else f'{r.tau:.2f}':>5} | {r.arm:>20} "
              f"{r.OOS_Sharpe:>9.3f} {r.OOS_CAGR:>9.2%} {r.OOS_MaxDD:>10.2%} | "
              f"{r.ctl_OOS_Sharpe:>7.3f} {r.v2_OOS_Sharpe:>6.3f} {r.spy_OOS_Sharpe:>6.3f} | "
              f"{'Y' if r.sign_held_OOS else 'n'}")
    w = W[W.arm != "(none)"]
    print(f"\n     mean OOS Sharpe by selector: " + "  ".join(
        f"{s} {w[w.sel==s].OOS_Sharpe.mean():.4f} (n={len(w[w.sel==s])})" for s in ("S1", "S2")))
    print(f"     mean OOS Sharpe by book: " + "  ".join(
        f"{b} {w[w.book==b].OOS_Sharpe.mean():.3f}" for b in order + ["V1u"]))
    s1 = w[w.sel == "S1"].set_index(["uni", "book", "cost"])
    for t in TAUS:
        s2 = w[(w.sel == "S2") & (w.tau == t)].set_index(["uni", "book", "cost"])
        j = s1.join(s2, rsuffix="_2", how="inner")
        chg = int((j.arm != j.arm_2).sum())
        print(f"     S2(tau={t:.2f}) changes {chg} of {len(j)} S1 picks; mean dOOS Sharpe "
              f"{(j.OOS_Sharpe_2 - j.OOS_Sharpe).mean():+.4f}; empty cells "
              f"{int((W[(W.sel=='S2') & (W.tau==t)].arm == '(none)').sum())}")
    print(f"     OOS sign of the picked denominator held in "
          f"{int(w.sign_held_OOS.sum())}/{len(w)} picks")

    print("\n\n[G] KEEP PATHS over every arm row")
    for c in PUB_COSTS:
        z = G[G.cost == c]
        print(f"     {c:>4.0f} bps: 4a (vs RULES v2) {int(z.p4a.sum())}/{len(z)}   "
              f"4a (vs RULES v1, idea 94's convention) {int(z.p4a_v1.sum())}/{len(z)}   "
              f"4b {int(z.p4b.sum())}/{len(z)}")
    print(f"     {'book':>6} | " + " | ".join(f"{c:.0f}bps 4a/4b" for c in PUB_COSTS))
    for b in order + ["V1u"]:
        cells = []
        for c in PUB_COSTS:
            z = G[(G.book == b) & (G.cost == c)]
            cells.append(f"{int(z.p4a.sum()):>3}/{int(z.p4b.sum()):<3} of {len(z)}")
        print(f"     {b:>6} | " + " | ".join(cells))
    k = G[G.p4b & (G.cost == 10.0)]
    if len(k):
        print("\n     4b passers at 10 bps:")
        for _, r in k.sort_values("Sharpe", ascending=False).iterrows():
            print(f"       {r.uni:>18} {r.book:>6} {r.arm:>20} CAGR {r.CAGR:>6.2%} "
                  f"Sharpe {r.Sharpe:.3f} MaxDD {r.MaxDD:>7.2%} H1/H2 {r.H1:.3f}/{r.H2:.3f} "
                  f"OOS {r.OOS_Sharpe:.3f} | 4b margins H1 {r.m4b_H1:+.3f} H2 {r.m4b_H2:+.3f} "
                  f"OOS {r.m4b_OOS:+.3f} DD {r.m4b_DD:+.4f} CAGR {r.m4b_CAGR:+.4f}")
    reconcile(G, D3)
    print(f"\n    wrote {SLUG}.grid.csv / .bootstrap.csv / .d3.csv / .walkforward.csv")


# ---------------------------------------------------------------- cross-lane reconciliation
def reconcile(G, D3):
    """Lane B ran this same queue idea independently on the same day.  Its committed d3.csv
    carries all three of idea 122's drop fractions, so the two published curves can be taken
    apart into their two possible causes: DIFFERENT SUB-PANELS (this run replicates idea 122's
    rng, lane B drew its own) and a DIFFERENT ADMISSIBILITY RULE (q fixed at idea 122's 0.10
    here, the sign required at all three q there).  Runs only if lane B's file is present;
    asserts nothing about lane B."""
    f = BT / "2026-09-07_book-size-floor-for-any-quoted-price_B.d3.csv"
    if not f.exists():
        return
    print("\n\n[H] RECONCILIATION with lane B's independent same-day run of this idea")
    b = pd.read_csv(f)
    b["book"] = b.book.replace({"TOPall": "ALL"})
    b10 = b[np.isclose(b.q, Q_STAR)]
    shared = sorted(set(D3.book) & set(b10.book))
    w = 0.0
    for bk in shared:
        a = D3[D3.book == bk].set_index(["uni", "arm"]).sort_index()
        c = b10[b10.book == bk].set_index(["uni", "arm"]).sort_index()
        j = a[["frac_pos_full"]].join(c[["frac_pos_full"]], rsuffix="_B", how="inner")
        d = float((j.frac_pos_full - j.frac_pos_full_B).abs().max())
        md = float((j.frac_pos_full - j.frac_pos_full_B).abs().mean()); w = max(w, d)
        print(f"    D3 draw fractions, {bk:>5}: {len(j)} arm-cells, mean|d| {md:.4f}, "
              f"max|d| {d:.3f} vs lane B")
    print(f"    -> the sub-panels are NOT the same draws (worst {w:.3f}): this run replays idea "
          f"122's rng,\n       lane B drew its own 40.  So the two published curves can differ "
          f"for two reasons, and the\n       next table separates them.")
    piv = b.pivot_table(index=["uni", "book", "arm"], columns="q", values="frac_pos_full")
    piv = piv.rename(columns={0.05: "f05", 0.10: "f10", 0.20: "f20"}).reset_index()
    g = G.merge(piv, on=["uni", "book", "arm"], how="left")
    g["ADM_B10"] = g.D1_pass & g.D2_pass & (g.f10 >= 0.90)                    # B's draws, one q
    g["ADM_allq"] = (g.D1_pass & g.D2_pass & (g.f05 >= 0.90) & (g.f10 >= 0.90)
                     & (g.f20 >= 0.90))                                       # B's draws, all q
    order = [f"TOP{n}" if n != "ALL" else "ALL" for n in NS]
    print(f"\n    u56 published share at tau=0.90, holding D1/D2 fixed (both lanes reproduce "
          f"idea 94 there):")
    print(f"     {'book':>6} {'pub':>4} | {'my draws, q=0.10':>17} {'B draws, q=0.10':>16} "
          f"{'B draws, all 3 q':>17} | {'lane B published':>17}")
    laneB = {"TOP3": 0.5556, "TOP5": 1.0000, "TOP10": 0.8636, "TOP20": 0.7273,
             "TOP40": 1.0000, "ALL": 0.9583}
    for bk in order:
        z = g[(g.book == bk) & (g.uni == UNIS[0][0]) & g.published]
        print(f"     {bk:>6} {len(z):>4} | {z['ADM_0.90'].mean():>17.4f} "
              f"{z.ADM_B10.mean():>16.4f} {z.ADM_allq.mean():>17.4f} | {laneB[bk]:>17.4f}")
    print("    Columns 2 and 3 are EQUAL at every rung and both reproduce lane B's committed "
          "u56 curve, so\n    the whole gap between the two lanes' published curves is DRAW "
          "NOISE in the 40 sub-panels —\n    the q convention (one drop fraction vs all three) "
          "adds nothing on u56.  That is a result about\n    idea 122's test, not about this "
          "ladder: at NDRAW = 40 the D3 statistic can move a rung's\n    published share by a "
          "third (TOP3 0.889 -> 0.556 on 18 rows) between two honest runs.  The\n    verdict — "
          "non-monotone in n, no statable floor — is identical under all three columns.")


if __name__ == "__main__":
    main()
